import React, {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Badge} from "@chakra-ui/react"
import { apiUtils} from '../utils'

export default function Home() {

  const [spell, setSpell] = useState("")
  const [data, setData] = useState()

  const grabSpell = () => {
    if (spell) {
      apiUtils.grabSpell(spell)
        .then(data => {
          setData(JSON.stringify(data))
        })
        .catch(console.error)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Badge>Default</Badge>
      <input type="input" onInput={e => setSpell(e.target.value)} placeholder="provide spell"/>
      <br/>
      <input type="button" onClick={grabSpell} value="Submit spell"/>
      <br/>
      {
        data && (
          <span>Spell Power: {data}</span>
        )
      }
    </div>
  )
}
