import {useRouter} from 'next/router'
import React, {useState} from 'react'
import Head from 'next/head'
import {Badge} from "@chakra-ui/react"
import {context} from '../../context/providers'
import {apiUtils} from '../../utils'

export default function Home() {
  const router = useRouter()
  const [spell, setSpell] = useState("")
  const [data, setData] = useState()
  let {state} = React.useContext(context);

  React.useEffect(() => {
    if (!state.isLoggedIn) {
      router.push('/', undefined, { shallow: true })
    }
  })

  const grabSpell = () => {
    if (spell) {
      apiUtils.grabSpell(spell)
        .then(data => {
          setData(JSON.stringify(data))
        })
        .catch(console.error)
    }
  }

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Badge>Default</Badge>
      <input type="input" onInput={e => setSpell(e.target.value)} placeholder="provide spell"/>
      <br/>
      <input type="button" onClick={grabSpell} value="Submit spell"/>
      <br/>
      {
        data && (
          <span>Spell Power: {data}</span>
        )
      }
    </div>
  )
}
